development:
  clients:
    default:
      database: discord_strava_development
      hosts:
        - 127.0.0.1:27017
  options:
    raise_not_found_error: false
    use_utc: true

test:
  clients:
    default:
      database: discord_strava_test
      hosts:
        - 127.0.0.1:27017
  options:
    raise_not_found_error: false
    use_utc: true

production:
  clients:
    default:
      uri: <%= ENV['MONGO_URL'] %>
  options:
    raise_not_found_error: false
    use_utc: true
